version: "3"


services: #corremos los servicos

  grafana: #la igual corremos grafana

    image: grafana/grafana   #ingresamos la direccion de imagen de grafana

    container_name: grafana #nombramos el contenedor de nuestro servicio

    restart: always #Le damos la orden de que siempre se inicie

    ports:       #asignamos el puerto
      - 3000:3000

    networks:             #Seleccionamos el nombre del networks
      - grafana_network

    volumes:          #Agregamos la direccion
      - grafana_data:/var/lib/grafana

    depends_on:   #Agregamos la dependencia
      - influxdb

  influxdb: #Iniciamos el servicio Influxdb

    image: influxdb:latest   #Colocamos la direccion de la imagen de grafana

    container_name: influxdb #Le asignamos un nombre para nuestro servicio

    restart: always #Le decimos que siempre se inicialice

    ports:  #Seleccionamos el puerto
      - 8086:8086

    networks:   #Seleccionamos el nombre del networks
      - grafana_network

    volumes:   #Agregamos la direccion
      - influxdb_data:/var/lib/influxdb

    environment: #Asignamos la cofiguracion de la base de datos
      - INFLUXDB_DB=grafana               #Asignamos nombre de la base de datos
      - INFLUXDB_USER=grafana             #Asignamos el usuario de la base de datos
      - INFLUXDB_USER_PASSWORD=password   #Asignamos el password para el usuario
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin         #Asignamos el nombre para el admin
      - INFLUXDB_ADMIN_PASSWORD=password  #configuramos la contraseña para el administrador

  nodered:   #Iniciamos el servicios

    container_name: Node-red   #Ingresamos el nombre del servicio

    image: nodered/node-red:latest #Agregamos la direccion de la imagen del node red

    restart: always #Le decimos que siempre se inicialice

    ports: #Le asignamos un puerto
      - 1880:1880

    networks: #Le configuramos el networds
      - grafana_network

    volumes: #Asignamos el volumen
      - nodered_data:/var/lib/nodered
networks:
  grafana_network:

volumes:   #Asignamos el volumenen de grafana, influxdb y nodered
  grafana_data:
  influxdb_data:
  nodered_data:
